COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."TOURISTS"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('tourists.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."TOURGUIDES"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('tourguides.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."AITRIPS"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('aitrips.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."AITRIP_PLACES"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('aitrip_places.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."CUSTOMTRIPS"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('customtrips.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."CUSTOMTRIP_DAYS"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('customtrips_days.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."CUSTOMTRIP_PLACES"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('customtrips_places.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."TOURGUIDETRIPS"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('tourguidetrips.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."TOURGUIDETRIP_DAYS"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('tourguidetrip_days.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."TOURGUIDETRIP_PLACES"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('tourguidetrip_places.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT


COPY INTO "EASY_TOUR_DB"."EASY_TOUR_SCH"."TOURGUIDETRIP_PLACES"
FROM '@"EASY_TOUR_DB"."EASY_TOUR_SCH"."GCS_STAGE"'
FILES = ('tourguidetrip_places.parquet')
FILE_FORMAT = (
    TYPE=PARQUET,
    REPLACE_INVALID_CHARACTERS=TRUE,
    BINARY_AS_TEXT=FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT
